import React, { useState } from 'react';
import { Lock, Mail, Eye, EyeOff, ShieldAlert, CheckCircle2, AlertCircle, ArrowRight, Building2, Landmark, User, Key } from 'lucide-react';
import { UserRole } from '../App.js';

interface OfficialLoginPageProps {
  onNavigate: (tab: string) => void;
  onLoginSuccess: (user: { email: string; token: string; role: UserRole; department?: string }) => void;
}

export const OfficialLoginPage: React.FC<OfficialLoginPageProps> = ({
  onNavigate,
  onLoginSuccess,
}) => {
  const [email, setEmail] = useState<string>('debasis6269@gmail.com');
  const [password, setPassword] = useState<string>('SetuOfficial#2026');
  const [showPassword, setShowPassword] = useState<boolean>(false);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const handleOfficialLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email || !email.includes('@') || !password) {
      setError('Please provide your official government/municipal email and password.');
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      const res = await fetch('/api/auth/official/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email: email.trim().toLowerCase(),
          password: password.trim(),
        }),
      });

      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.message || data.error || 'Authentication rejected by sovereign security gate.');
      }

      const role = (data.role as UserRole) || 'policymaker';
      onLoginSuccess({
        email: email.trim().toLowerCase(),
        token: data.token,
        role,
        department: data.user?.department,
      });

      // Route to destination dashboard
      if (role === 'governance_officer') {
        onNavigate('governance');
      } else {
        onNavigate('policymaker');
      }
    } catch (err: any) {
      setError(err.message || 'Error signing in as official.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div style={{
      maxWidth: 960,
      margin: '40px auto',
      padding: '0 20px',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
    }}>
      {/* Sovereign Clearance Badge */}
      <div style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: 8,
        padding: '6px 16px',
        borderRadius: 'var(--radius-full)',
        backgroundColor: 'rgba(234, 179, 8, 0.12)',
        border: '1px solid rgba(234, 179, 8, 0.3)',
        color: '#ca8a04',
        fontWeight: 700,
        fontSize: '12px',
        marginBottom: 20,
      }}>
        <ShieldAlert size={16} />
        <span>SOVEREIGN MUNICIPAL CLEARANCE · RESTRICTED ACCESS</span>
      </div>

      {/* Main Login Card */}
      <div style={{
        width: '100%',
        maxWidth: 520,
        backgroundColor: 'var(--bg-surface)',
        borderRadius: 24,
        padding: '36px 32px',
        boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.15), 0 0 0 1px var(--border-subtle)',
        border: '1px solid var(--border-subtle)',
      }}>
        <div style={{ textAlign: 'center', marginBottom: 26 }}>
          <div style={{
            width: 48,
            height: 48,
            borderRadius: 16,
            backgroundColor: 'rgba(0, 97, 148, 0.1)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            margin: '0 auto 16px',
            color: '#006194',
          }}>
            <Landmark size={24} />
          </div>
          <h1 style={{
            fontSize: '24px',
            fontWeight: 800,
            color: 'var(--text-primary)',
            marginBottom: 8,
            letterSpacing: '-0.02em',
          }}>
            Official Authority Portal
          </h1>
          <p style={{
            fontSize: '13px',
            color: 'var(--text-secondary)',
            lineHeight: 1.5,
          }}>
            Sign in with credentials generated by the Super Administrator to access cluster analytics, budget co-financing, and AI governance audit ledgers.
          </p>
        </div>

        {error && (
          <div style={{
            display: 'flex',
            alignItems: 'center',
            gap: 10,
            padding: '12px 16px',
            borderRadius: 12,
            backgroundColor: 'rgba(239, 68, 68, 0.1)',
            border: '1px solid rgba(239, 68, 68, 0.3)',
            color: '#ef4444',
            fontSize: '13px',
            marginBottom: 20,
          }}>
            <AlertCircle size={16} style={{ flexShrink: 0 }} />
            <span>{error}</span>
          </div>
        )}

        <form onSubmit={handleOfficialLogin} style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
          <div>
            <label style={{
              display: 'block',
              fontSize: '13px',
              fontWeight: 600,
              color: 'var(--text-primary)',
              marginBottom: 8,
            }}>
              Official Government / Authority Email
            </label>
            <div style={{ position: 'relative' }}>
              <Mail size={18} style={{
                position: 'absolute',
                left: 14,
                top: '50%',
                transform: 'translateY(-50%)',
                color: 'var(--text-muted)',
              }} />
              <input
                type="email"
                required
                placeholder="official@municipality.gov.in"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                style={{
                  width: '100%',
                  padding: '12px 14px 12px 42px',
                  borderRadius: 12,
                  border: '1px solid var(--border-subtle)',
                  backgroundColor: 'var(--bg-app)',
                  color: 'var(--text-primary)',
                  fontSize: '14px',
                  boxSizing: 'border-box',
                  outline: 'none',
                }}
              />
            </div>
          </div>

          <div>
            <label style={{
              display: 'block',
              fontSize: '13px',
              fontWeight: 600,
              color: 'var(--text-primary)',
              marginBottom: 8,
            }}>
              Admin-Generated Password
            </label>
            <div style={{ position: 'relative' }}>
              <Lock size={18} style={{
                position: 'absolute',
                left: 14,
                top: '50%',
                transform: 'translateY(-50%)',
                color: 'var(--text-muted)',
              }} />
              <input
                type={showPassword ? 'text' : 'password'}
                required
                placeholder="Enter password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                style={{
                  width: '100%',
                  padding: '12px 44px 12px 42px',
                  borderRadius: 12,
                  border: '1px solid var(--border-subtle)',
                  backgroundColor: 'var(--bg-app)',
                  color: 'var(--text-primary)',
                  fontSize: '14px',
                  boxSizing: 'border-box',
                  outline: 'none',
                }}
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                style={{
                  position: 'absolute',
                  right: 12,
                  top: '50%',
                  transform: 'translateY(-50%)',
                  background: 'none',
                  border: 'none',
                  color: 'var(--text-muted)',
                  cursor: 'pointer',
                  padding: 4,
                  display: 'flex',
                  alignItems: 'center',
                }}
              >
                {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
              </button>
            </div>
          </div>

          {/* Preset Helper Card for Quick Access */}
          <div style={{
            padding: '12px 14px',
            borderRadius: 12,
            backgroundColor: 'rgba(0, 97, 148, 0.05)',
            border: '1px solid rgba(0, 97, 148, 0.15)',
            fontSize: '12px',
            color: 'var(--text-secondary)',
          }}>
            <div style={{ fontWeight: 700, color: '#006194', marginBottom: 4, display: 'flex', alignItems: 'center', gap: 6 }}>
              <Key size={13} />
              <span>Configured Authority Accounts:</span>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
              <div>
                <strong>Super Admin:</strong> <code>debasispanigrahi7864@gmail.com</code> (Pass: <code>SetuAdmin#2026</code>)
              </div>
              <div>
                <strong>Municipal Official:</strong> <code>debasis6269@gmail.com</code> (Pass: <code>SetuOfficial#2026</code>)
              </div>
            </div>
          </div>

          <button
            type="submit"
            disabled={isLoading}
            style={{
              width: '100%',
              padding: '14px',
              borderRadius: 12,
              backgroundColor: '#006194',
              color: '#ffffff',
              border: 'none',
              fontWeight: 700,
              fontSize: '14px',
              cursor: isLoading ? 'not-allowed' : 'pointer',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: 8,
              boxShadow: '0 4px 14px rgba(0, 97, 148, 0.3)',
              marginTop: 4,
            }}
          >
            <span>{isLoading ? 'Verifying Sovereign Clearance...' : 'Authenticate & Unlock Authority View'}</span>
            <ArrowRight size={16} />
          </button>
        </form>

        {/* Link back to Citizen Login */}
        <div style={{
          marginTop: 28,
          paddingTop: 20,
          borderTop: '1px solid var(--border-subtle)',
          textAlign: 'center',
        }}>
          <p style={{ fontSize: '13px', color: 'var(--text-secondary)', marginBottom: 8 }}>
            Are you a citizen reporting a broken road or water outage?
          </p>
          <button
            onClick={() => onNavigate('citizen-login')}
            style={{
              background: 'transparent',
              border: '1px solid var(--border-subtle)',
              padding: '8px 16px',
              borderRadius: 10,
              color: 'var(--text-primary)',
              fontSize: '13px',
              fontWeight: 700,
              cursor: 'pointer',
              display: 'inline-flex',
              alignItems: 'center',
              gap: 6,
            }}
          >
            <User size={14} style={{ color: '#006194' }} />
            <span>← Go to Citizen Login (Passwordless OTP)</span>
          </button>
        </div>
      </div>
    </div>
  );
};
